{
	"version": 1603697714,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/spritefont.png",
		"images/sprite3-sheet0.png",
		"images/bg-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/ground-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/player-sheet4.png",
		"images/kiri-sheet0.png",
		"images/kanan-sheet0.png",
		"images/atas-sheet0.png",
		"images/papanskor-sheet0.png",
		"images/musuh1-sheet0.png",
		"images/musuh2-sheet0.png",
		"images/musuh3-sheet0.png",
		"images/mk1-sheet0.png",
		"images/mk2-sheet0.png",
		"images/mk3-sheet0.png",
		"images/mk4-sheet0.png",
		"images/mk5-sheet0.png",
		"images/star-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/play-sheet0.png",
		"images/sprite7-sheet0.png",
		"media/anyconv.com__sound makan.ogg",
		"media/anyconv.com__game over.ogg",
		"media/anyconv.com__backsound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}